# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "takler"
copyright = "2022-2026, cemc-oper"
author = "perillaroc"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.mermaid",
    "sphinx_design",
]

# 让标准库类型（``datetime.datetime``、``typing.Literal`` 等）的交叉引用能解析到
# 官方 Python 文档，而不是在 nitpicky 模式下报“找不到目标”。
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# 严格模式：交叉引用目标缺失时报 warning（配合 `-W` 即失败），
# 用于在文档构建阶段捕获断链的 `:py:class:` / `:py:func:` 等引用。
nitpicky = True

# 允许缺失的交叉引用目标。批次 R（T40~T42）补齐 API 页后，早前列在这里的
# SerializationType / Calendar / NodeStatus 成员与三个异常条目已全部可从
# API 页解析，不再出现。新增条目时注明原因，而不是关闭 nitpicky。
nitpick_ignore = [
    # typing 中的容器/别名类型不在本项目文档范围内。
    ("py:class", "typing.Any"),
    # 可选第三方库（gRPC、textual、loguru 等）的类型不进 intersphinx，
    # client / tui 模块 docstring 里的引用保持为本地说明性文字。
    ("py:class", "grpc.ChannelCredentials"),
    ("py:class", "grpc.ServerCredentials"),
    ("py:class", "grpc.StatusCode"),
    ("py:class", "grpc.aio.ServerInterceptor"),
    ("py:func", "grpc.ssl_server_credentials"),
    ("py:class", "pydantic.config.ConfigDict"),
    ("py:class", "rich.text.Text"),
    ("py:class", "textual.geometry.Offset"),
    ("py:class", "textual.widgets.OptionList"),
    # sphinx-autodoc-typehints 渲染 ``Literal[NodeStatus.queued, ...]`` 注解时
    # 使用对象的真实模块路径（takler.core.state.*），而 NodeStatus 在 API 页
    # 按公开路径 takler.core.NodeStatus 收录，两条引用无法对上。
    ("py:attr", "takler.core.state.NodeStatus.queued"),
    ("py:attr", "takler.core.state.NodeStatus.complete"),
    # ``RepeatBase`` 是 ``Generic[T]``，类型注解里的 TypeVar ``T`` 没有文档目标。
    ("py:class", "takler.core.repeat.T"),
    # sphinx-autodoc-typehints 渲染 ``Optional[TreeNode[str]]`` （非
    # ``from __future__ import annotations`` 模块）时，下标里的 ``str``
    # 被 repr 成 ``class 'str'`` 再包成引用，目标天然不存在。
    ("py:class", "class 'str'"),
    # Python < 3.14 上 ``contextvars.Token.__module__`` 是私有模块
    # ``_contextvars``，autodoc 按真实模块为 auth.py 里
    # ``set_call_credentials`` / ``reset_call_credentials`` 的注解建引用，
    # 而私有模块不进 Python 官方文档，intersphinx 解析不到。
    ("py:class", "_contextvars.Token"),
]

# 系统性的允许缺失模式（re.fullmatch 匹配）。本项目 docstring 的约定是：
# 枚举成员与模块级常量在所属类 / 模块的 docstring 里以散文说明，不注册为独立
# 文档目标；下划线开头的私有成员不进 API 页。对它们的交叉引用因此没有目标，
# 用正则说明原因，而不是逐个列出或关闭 nitpicky。
nitpick_ignore_regex = [
    # 全大写名字：枚举成员（ ``AuthMode.DISABLED`` 、 ``LogLevel.INFO`` 等）与
    # 模块级常量（ ``EXIT_OK`` 、 ``MAX_BACKOFF_SECONDS`` 、 ``_CALL_CREDENTIALS``
    # 等）。
    ("py:attr", r"(?:[a-zA-Z0-9_.]*\.)?_?[A-Z][A-Z0-9_]*"),
    ("py:data", r"(?:[a-zA-Z0-9_.]*\.)?_?[A-Z][A-Z0-9_]*"),
    # 私有成员： ``_guard_child_command`` 、 ``_CredentialFile`` 等。
    ("py:meth", r"(?:[a-zA-Z0-9_.]*\.)?_[a-zA-Z0-9_]+"),
    ("py:func", r"(?:[a-zA-Z0-9_.]*\.)?_[a-zA-Z0-9_]+"),
    ("py:class", r"(?:[a-zA-Z0-9_.]*\.)?_[a-zA-Z0-9_]+"),
]

# linkcheck 构建（`-b linkcheck`）中允许跳过的链接模式：
# - stackoverflow.com 对非浏览器客户端一律返回 403，链接本身有效；
# - github.com/cemc-oper/* 在项目构建环境（内网）不可达，链接本身有效。
linkcheck_ignore = [
    r"https://stackoverflow\.com/",
    r"https://github\.com/cemc-oper/",
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinx_book_theme'
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "github_url": "https://github.com/cemc-oper/takler",
    # 顶层 toctree 中的每一项（教程/用户指南/运维/开发者）会分别展示为顶部横条上的一个
    # 菜单，有子页面的项会带下拉列表。四个分类落在该阈值内，不会被折叠进「More」下拉菜单。
    "header_links_before_dropdown": 5,
    "navigation_with_keys": False,
    "show_toc_level": 2,
    "use_edit_page_button": False,
}
html_title = "Takler文档"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

autosummary_generate = True

# sphinx-autodoc-typehints 默认按构建所用解释器的 repr 渲染 ``Union``：Python
# < 3.14 得到 ``typing.Union[int, str]``，并给 ``typing.Union`` 建交叉引用——
# 该别名已从最新版 Python 文档移除，intersphinx 解析不到，nitpicky + ``-W``
# 下直接失败；3.14 起 repr 才是 ``int | str``。强制竖线写法让 API 页在所有
# 受支持的 Python 版本（CI 矩阵 3.11/3.12，Read the Docs 3.12）下渲染一致。
always_use_bars_union = True

# 可选依赖（tui / log extras）在只装 docs 依赖组的环境（如 Read the Docs，
# 见 .readthedocs.yml）里不存在。autodoc 遇到这些导入失败时用 mock 顶替，
# 使 develop/api 的 tui.rst 与 logging.rst 在任何环境都能通过严格构建；
# 本地已安装对应库时仍使用真实导入（mock 只是后备）。
autodoc_mock_imports = ["textual", "rich", "loguru"]
