# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "takler"
copyright = "2022, cemc-oper"
author = "perillaroc"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.mermaid",
    "sphinx_design",
]

# 让标准库类型（``datetime.datetime``、``typing.Literal`` 等）的交叉引用能解析到
# 官方 Python 文档，而不是在 nitpicky 模式下报“找不到目标”。
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# 严格模式：交叉引用目标缺失时报 warning（配合 `-W` 即失败），
# 用于在文档构建阶段捕获断链的 `:py:class:` / `:py:func:` 等引用。
nitpicky = True

# 允许缺失的交叉引用目标：本项目 API 页面尚未覆盖的对象（覆盖计划见
# doc/documentation-plan.md 批次 R），在此显式列出并注明原因，而不是关闭 nitpicky。
nitpick_ignore = [
    # typing 中的容器/别名类型不在本项目文档范围内。
    ("py:class", "typing.Any"),
    # 以下对象在源码中已用 :py:class: / :py:exc: / :py:attr: / :py:obj: 交叉引用，
    # 但对应的 API 页面（tree.rst / attribute.rst / exceptions.rst 等）尚未补齐
    # 这些条目，计划在批次 R（T40~T42）随对应页面一并从本列表移除。
    ("py:class", "takler.core.util.SerializationType"),
    ("py:obj", "takler.core.SerializationType.Status"),
    ("py:obj", "takler.core.SerializationType.Tree"),
    ("py:class", "takler.core.calendar.Calendar"),
    ("py:attr", "takler.core.state.NodeStatus.queued"),
    ("py:attr", "takler.core.state.NodeStatus.complete"),
    ("py:exc", "ExpressionSyntaxError"),
    ("py:exc", "FlowStateError"),
    ("py:exc", "JobSubmissionError"),
]

# linkcheck 构建（`-b linkcheck`）中允许跳过的链接模式，例如尚未发布的锚点或
# 本地开发环境专用地址。目前为空，后续任务如遇到需要跳过的外部链接再补充。
linkcheck_ignore = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'sphinx_rtd_theme'
# html_theme = 'sphinx_book_theme'
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "github_url": "https://github.com/cemc-oper/takler",
    # 顶层 toctree 中的每一项（教程/运维/开发者）会分别展示为顶部横条上的一个菜单，
    # 有子页面的项会带下拉列表。这里设为较大值以避免被折叠进「More」下拉菜单。
    "header_links_before_dropdown": 5,
    "navigation_with_keys": False,
    "show_toc_level": 2,
    "use_edit_page_button": False,
}
html_title = "Takler文档"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

autosummary_generate = True
