"""Job tab: dump the job script generated by takler.

Server-side, ``ShellScriptTaskGeneratedParameters`` derives the job
script path from ``TAKLER_HOME`` plus the node's path and try number::

    TAKLER_JOB = TAKLER_HOME + node_path + ".job" + try_no

The generated file is the rendered Jinja template (``.takler``) flattened
into a runnable shell script. We reuse the same rule to find it from the
TUI's snapshot of the bunch.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from textual import work

from ..show_parser import NodeInfo, ShowSnapshot
from ._artifacts import artifact_prefix
from ._fileview import _FileViewTab


class JobTab(_FileViewTab):
    """Render the takler-generated job script for the selected task."""

    _TAB_ID = "tab-job"
    _BODY_ID = "job-body"

    DEFAULT_CSS = """
    JobTab { padding: 1 2; }
    JobTab Static.title { padding-bottom: 1; text-style: bold; }
    JobTab #job-body { height: 1fr; }
    """

    def show_node(
        self,
        node: Optional[NodeInfo],
        snapshot: Optional[ShowSnapshot] = None,
    ) -> None:
        if node is None:
            self._show_empty()
            return

        prefix = artifact_prefix(node, snapshot)
        if prefix is None:
            self._show_no_job(node.path)
            return

        # Picking the job file scans a directory (iterdir + stat), so do
        # it on a worker together with the read.
        self._title.update(f"{node.path}: loading…")
        self._load_job(node.path, prefix)

    def _show_no_job(self, node_path: str) -> None:
        self._show_message(
            f"{node_path}: no job script yet",
            "No job script found. The task may not have been "
            "dispatched yet, or TAKLER_HOME is not visible to "
            "the TUI host.",
        )

    @work(thread=True, exclusive=True, group="job")
    def _load_job(self, node_path: str, prefix: Path) -> None:
        candidate = self._pick_job(prefix)
        text: Optional[str] = None
        error: Optional[str] = None
        if candidate is not None:
            try:
                text = candidate.read_text(errors="replace")
            except OSError as exc:
                error = f"read error: {exc}"
        self.app.call_from_thread(self._apply_job, node_path, candidate, text, error)

    def _apply_job(
        self,
        node_path: str,
        candidate: Optional[Path],
        text: Optional[str],
        error: Optional[str],
    ) -> None:
        if candidate is None:
            self._show_no_job(node_path)
            return
        # Reuse the shared renderer for the success / read-error path.
        self._apply_file(node_path, candidate, text, error)

    @staticmethod
    def _pick_job(prefix: Path) -> Optional[Path]:
        # Most common case: try_no == 0 → '<prefix>.job0'
        candidate = Path(f"{prefix}.job0")
        if candidate.exists():
            return candidate

        # Otherwise pick the newest '<prefix>.job<digit>+'.
        parent = prefix.parent
        if not parent.exists():
            return None
        stem = prefix.name + ".job"
        candidates: List[Path] = []
        try:
            for entry in parent.iterdir():
                if not entry.is_file():
                    continue
                name = entry.name
                if not name.startswith(stem):
                    continue
                suffix = name[len(stem) :]
                if suffix.isdigit():
                    candidates.append(entry)
        except OSError:
            return None

        if not candidates:
            return None
        candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return candidates[0]
